### ISSUE TITLE
Install Django and related packages

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#1]
As a Developer, I can setup my workspace, so that I can start working on the project

## Acceptance Criteria
- Correct Django version installed

- Other related packages installed 

## Tasks
- [x] Install Django
- [x] Install dj_database_url psycopg2
- [x] Install django-crispy-forms
- [x] Install crispy bootstrap
- [x] Install Gunicorn
- [x] Update settings.py
- [x] Update requirements.txt
- [x] Update env.py
