### ISSUE TITLE
Landing page links, motto and description cards

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#10]
As a Shopper, I can find more description about product categories and business profile, so that I can make better purchasing decisions

## Acceptance Criteria
- Product category cards present with description

- Motto present

## Tasks
- [x] Create product category cards with Bootstrap
- [x] Add links to cards
- [x] Create business motto
