### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#11]
As a Shopper, I can find some additional information about the business, so that I can get to know it better

## Acceptance Criteria
- Footer present across site

- Footer contains social media links, disclaimer, placeholders for privacy policy link and subscribe to newsletter form 

## Tasks
- [x] Create footer template
- [x] Add social media links
- [x] Add disclaimer
- [x] Add placeholders for privacy policy link and subscribe to newsletter form
