### ISSUE TITLE
All auth set up

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#12]
As a Business owner, I can restrict user access based on permissions, so that I can achieve good security on the site

## Acceptance Criteria
- All auth installed 

- Links for register, log in, log out working

## Tasks
- [x] Install all auth
- [x] Locate and copy all auth templates
- [x] Add links to navbar
