### ISSUE TITLE
Shoppers can view products

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#15]
As a Shopper, I can view products, so that I can decide whether to buy them

## Acceptance Criteria
- Products created in database

## Tasks
- [x] Create product model
- [x] Create views and urls
- [x] Upload products to database
