### ISSUE TITLE
Shoppers can view checkout

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#23]
As a Shopper, I can view checkout, so that I can complete it

## Acceptance Criteria
- Checkout page and form displaying correctly

## Tasks
- [x] Create checkout form
- [x] Create checkout template
- [x] Style checkout template
