### ISSUE TITLE
Shoppers can read stories on the site

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#27]
As a Shoppers, I can read stories, so that I can get in the right mood

## Acceptance Criteria
- Stories app working

## Tasks
- [x] Create story model
- [x] Create story views & urls
- [x] Create story templates
