### ISSUE TITLE
Product CRUD for admin users in the site UI

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#29]
As a store owner/admin, I can add and update products without going to admin UI, so that it's more efficient

## Acceptance Criteria
- Admin can add products via custom form on the website

- Admin can update products via custom form on the website

## Tasks
- [ ] Add product view, template, form
- [ ] Edit product view, template, form
- [ ] Delete product view
