### ISSUE TITLE
First Heroku deployment

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#4]
As a Developer, I can verify that initial settings are working correctly, so that I can continue with the project

## Acceptance Criteria
- App successfully deployed on Heroku

## Tasks
- [x] Create new Heroku app
- [x] Ensure required config vars are added
- [x] Set up manual deployment from GitHub
