### ISSUE TITLE
Landing page set up

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#6]
As a Shopper, I can see information about the store, so that I can find out about their business

## Acceptance Criteria
- Landing page displays successfully

## Tasks
- [x] Create index.html
- [x] Create home view
- [x] Create home urls
