### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#7]
As a Shopper, I can navigate the site easily, so that I can get what I want

## Acceptance Criteria
- Navbar is working and responsive

- Placeholder for yet unimplemented pages present

## Tasks
- [x] Create navbar with Bootstrap for wide screen 
- [x] Consider creating mobile navbar in separate template
- [x] Insert required links and placeholders
- [x] Add icons where required
