### ISSUE TITLE
Logo and favicon

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#8]
As a Shopper, I can visually identify the store logo or icon, so that I see it among other tabs and recognize the brand

## Acceptance Criteria
- Logo present on the site

- Favicon showing on site tab

## Tasks
- [x] Create logo in Canva
- [x] Place logo in Navbar
- [x] Create favicon
- [x] Add favicon to base.html
