### ISSUE TITLE
Landing page basic styling and hero image

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/a-little-dream#9]
As a Shopper, I can enjoy the home page aesthetics, so that I understand the business is serious about user experience

## Acceptance Criteria
- Photos are of good quality and relevant to business operational profile
- Elements have visually appealing and sensible proportions and distance from each other
- Colors and photos match visually

## Tasks
- [x] Add hero images
- [x] Choose main color themes
- [x] Position elements according to design
- [x] Style elements size
